---
version: "3"

services:
  microtoken:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3700:3700"
    env_file:
      - /opt/docker/microtoken/fastapi/.env
    restart: always
